name: helloGithubAction  # 워크플로우 이름

on: [push]               # 'push' 이벤트 발생 시 실행

jobs:          # job 시작 
  build:  
    runs-on: ubuntu-latest  # 실행 환경
    steps:                # job 내부 실행 단계
    # 아무것도 없는 os에서 자동으로 우리의 코드를 클론하고 다운받아 실행하게 해줌
    - uses: actions/checkout@v2 # 다른사람이 만든 action 사용
    - name: 1. 파일목록 출력
      run: ls -al
    - name: 2. 파이썬 패키지 확인
      run: pip list
    - name: 3. 파이썬 실행
      run: python test.py