name: helloGithubAction  # 워크플로우 이름

on:
  schedule:
    - cron: "* /5 * * * *"  # 10분마다 실행(최소5분)  [분 시 일 월 요일] 
    #ex) 0 0 * * * 매일 0시 0분에 실행


jobs:          # job 시작 
  build:  
    runs-on: ubuntu-latest  # 실행 환경
    steps:                # job 내부 실행 단계
    # 아무것도 없는 os에서 자동으로 우리의 코드를 클론하고 다운받아 실행하게 해줌
    - uses: actions/checkout@v2 # 다른사람이 만든 action 사용
    - name: 1. 파일목록 출력
      run: ls -al
    - name: 2. 파이썬 패키지 확인
      run: pip list
    - name: 3. pip 업그레이드
      run: pip install --upgrade pip
    - name: 4. 필요한 패키지 설치
      run: pip install -r requirements.txt
    - name: 5. 파이썬 실행
      run: python test.py
    